### ISSUE TITLE
docker command is not working

### ISSUE THREAD

**Issue by sumutcan** [pldn/LDWizard#66]
Hi,
I believe there is something wrong with the docker build. The command in the readme file 
`docker build -f ./docker/Dockerfile -t "my-tag" --build-arg CONFIG_FILE=config.ts`

is not running, as the context is missing. When I put the LDWizard folder as the context, then it starts building the image however at the `yarn` command I get the following error:

> warning package.json: License should be a valid SPDX license expression
> error Couldn't find the binary ldwizard-build

it is also strange that the config.ts is in webpack, however that folder is not visited in the dockerfile.

thanks in advance
Umut

**Comment by vemonet** [comment]
Hi @sumutcan the context seems to be the root folder of the repository (the command you pasted miss the `.` btw), if the config is in the webpack folder then it should be in the CONFIG_FILE path:

```bash
docker build -f ./docker/Dockerfile -t "my-tag" --build-arg CONFIG_FILE=webpack/config.ts .
```

Note that the `docker-compose.yml` works well, it uses the root folder as context and point to a config in the webpack folder: `./webpack/runtimeConfig.ts`

```yaml
version: '3'
services:
  ldwizard:
    image: ldwizard/nde:1.0.0
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        CONFIG_FILE: ./webpack/runtimeConfig.ts
    ports:
      - "4000:80"
```
